In [1]:
import pandas as pd

path = r"C:\Users\HP\OneDrive\Escritorio\David Guzzi\Github\DGKaggle\Playground Series\Season 6\Episode 1 - Predicting Student Test Scores\data\train.csv"

df = pd.read_csv(path)
df.head(1)

,id,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score
0,0,21,female,b.sc,7.91,98.8,no,4.9,average,online videos,low,easy,78.3

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 630000 entries, 0 to 629999
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                630000 non-null  int64
 1   age               630000 non-null  int64
 2   gender            630000 non-null  object
 3   course            630000 non-null  object
 4   study_hours       630000 non-null  float64
 5   class_attendance  630000 non-null  float64
 6   internet_access   630000 non-null  object
 7   sleep_hours       630000 non-null  float64
 8   sleep_quality     630000 non-null  object
 9   study_method      630000 non-null  object
 10  facility_rating   630000 non-null  object
 11  exam_difficulty   630000 non-null  object
 12  exam_score        630000 non-null  float64
dtypes: float64(4), int64(2), object(7)
memory usage: 62.5+ MB

In [5]:
df.groupby(['exam_difficulty']).agg({'exam_score':'count'})

                 exam_score
exam_difficulty
easy                 176540
hard                  99478
moderate             353982

In [8]:
df.groupby(['exam_difficulty']).agg({'exam_score':'min'})

                 exam_score
exam_difficulty
easy                 19.599
hard                 19.599
moderate             19.599

In [9]:
path_2 = r"C:\Users\HP\OneDrive\Escritorio\David Guzzi\Github\DGKaggle\Playground Series\Season 6\Episode 1 - Predicting Student Test Scores\data\test.csv"

df_test = pd.read_csv(path_2)
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270000 entries, 0 to 269999
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                270000 non-null  int64
 1   age               270000 non-null  int64
 2   gender            270000 non-null  object
 3   course            270000 non-null  object
 4   study_hours       270000 non-null  float64
 5   class_attendance  270000 non-null  float64
 6   internet_access   270000 non-null  object
 7   sleep_hours       270000 non-null  float64
 8   sleep_quality     270000 non-null  object
 9   study_method      270000 non-null  object
 10  facility_rating   270000 non-null  object
 11  exam_difficulty   270000 non-null  object
dtypes: float64(3), int64(2), object(7)
memory usage: 24.7+ MB